export const areaGroups = [
  {
    "title": "Farnborough & the Blackwater Valley",
    "places": [
      "Farnborough",
      "Cove",
      "Southwood",
      "North Camp",
      "Farnborough Park",
      "Farnborough Street",
      "Aldershot",
      "Ash",
      "Ash Vale",
      "Ash Green",
      "Tongham",
      "Mytchett",
      "Frimley",
      "Frimley Green",
      "Camberley",
      "Deepcut",
      "Blackwater",
      "Hawley",
      "Yateley",
      "Frogmore",
      "Darby Green",
      "Sandhurst",
      "Crowthorne"
    ]
  },
  {
    "title": "Fleet, Hook & Basingstoke",
    "places": [
      "Fleet",
      "Church Crookham",
      "Crookham Village",
      "Elvetham Heath",
      "Dogmersfield",
      "Hartley Wintney",
      "Eversley",
      "Bramshill",
      "Winchfield",
      "Hook",
      "Odiham",
      "North Warnborough",
      "Greywell",
      "Rotherwick",
      "Long Sutton",
      "Upton Grey",
      "South Warnborough",
      "Newnham",
      "Old Basing",
      "Basingstoke",
      "Sherfield on Loddon",
      "Bramley"
    ]
  },
  {
    "title": "Farnham, Alton & nearby villages",
    "places": [
      "Farnham",
      "Hale",
      "Upper Hale",
      "Heath End",
      "Weybourne",
      "Badshot Lea",
      "Runfold",
      "Wrecclesham",
      "Rowledge",
      "The Bourne",
      "Frensham",
      "Tilford",
      "Churt",
      "Elstead",
      "Seale",
      "The Sands",
      "Bentley",
      "Froyle",
      "Crondall",
      "Ewshot",
      "Holybourne",
      "Alton",
      "Bordon",
      "Whitehill",
      "Lindford",
      "Headley",
      "Liphook"
    ]
  },
  {
    "title": "Guildford, Godalming & the Surrey Hills",
    "places": [
      "Guildford",
      "Normandy",
      "Wanborough",
      "Worplesdon",
      "Wood Street Village",
      "Fairlands",
      "Jacobs Well",
      "Burpham",
      "Merrow",
      "Shalford",
      "Chilworth",
      "Gomshall",
      "Shere",
      "Albury",
      "Godalming",
      "Farncombe",
      "Compton",
      "Puttenham",
      "Milford",
      "Witley",
      "Thursley",
      "Hindhead",
      "Beacon Hill",
      "Haslemere",
      "Grayshott",
      "Chiddingfold",
      "Bramley, Surrey",
      "Wonersh",
      "Shamley Green",
      "Cranleigh"
    ]
  },
  {
    "title": "Woking & north-west Surrey",
    "places": [
      "Woking",
      "Knaphill",
      "Brookwood",
      "Pirbright",
      "Bisley",
      "West End",
      "Chobham",
      "Lightwater",
      "Bagshot",
      "West Byfleet",
      "Byfleet",
      "Pyrford",
      "Ripley",
      "Send",
      "Old Woking",
      "Horsell",
      "Mayford",
      "Ottershaw",
      "Addlestone",
      "New Haw",
      "Chertsey",
      "Weybridge",
      "Walton-on-Thames",
      "Hersham",
      "Cobham",
      "Esher"
    ]
  },
  {
    "title": "Bracknell, Ascot & Windsor",
    "places": [
      "Bracknell",
      "Binfield",
      "Warfield",
      "Winkfield",
      "Winkfield Row",
      "Ascot",
      "South Ascot",
      "North Ascot",
      "Sunninghill",
      "Sunningdale",
      "Virginia Water",
      "Englefield Green",
      "Egham",
      "Egham Hythe",
      "Thorpe",
      "Staines-upon-Thames",
      "Wraysbury",
      "Old Windsor",
      "Windsor",
      "Datchet",
      "Eton",
      "Slough",
      "Maidenhead",
      "Holyport",
      "Bray"
    ]
  },
  {
    "title": "Wokingham, Reading & nearby villages",
    "places": [
      "Wokingham",
      "Finchampstead",
      "Barkham",
      "Arborfield",
      "Arborfield Green",
      "Shinfield",
      "Spencers Wood",
      "Three Mile Cross",
      "Swallowfield",
      "Riseley",
      "Farley Hill",
      "Winnersh",
      "Sindlesham",
      "Hurst",
      "Twyford",
      "Ruscombe",
      "Woodley",
      "Earley",
      "Lower Earley",
      "Reading",
      "Sonning",
      "Shiplake",
      "Burghfield",
      "Burghfield Common",
      "Mortimer Common"
    ]
  }
];
export const serviceAreas = areaGroups.flatMap(group => group.places);
