import React from 'react';
import {Link} from 'react-router-dom';

export default function Privacy(){return <>
<section className="page-head"><div className="container"><div className="eyebrow">YOUR INFORMATION</div><h1>Privacy notice.</h1><p>How CSC Property Solutions Ltd handles information when you browse this website or ask about driveway and patio cleaning.</p></div></section>
<section className="section privacy-content"><p className="privacy-date">Last updated: 2 October 2026</p>
<article><h2>Who to contact</h2><p>CSC Property Solutions Ltd is responsible for the personal information it uses to respond to enquiries and arrange cleaning work. For questions about your information or to make a privacy request, email <a href="mailto:caeleb@cscpropertysolutionsltd.co.uk">caeleb@cscpropertysolutionsltd.co.uk</a> or call <a href="tel:07765641219">07765 641219</a>.</p></article>
<article><h2>What information we receive</h2><p>The enquiry form asks for your name, phone number, email address, postcode and a description of the work you need. If you contact us directly, we also receive the details you choose to share, such as a property address, photographs or access arrangements.</p><p>Please only send information needed to discuss your cleaning job. Do not include payment-card details, identity documents, medical information or other sensitive details. You can call or email instead of using the form. Without enough contact and job information, we may be unable to reply or prepare a quote.</p></article>
<article><h2>Why we use your information</h2><p>We use enquiry details to respond, check coverage, discuss your surfaces, prepare a quotation and arrange requested work. For a personal quotation or booking, the lawful basis is taking steps at your request before a contract, or performing that contract.</p><p>For general or business enquiries and necessary security measures, we rely on legitimate interests in answering customers and protecting the service. Where records must be kept to meet tax or other legal requirements, the basis is legal obligation. Sending this form does not subscribe you to a marketing list. This website does not make automated decisions about you that have legal or similarly significant effects.</p></article>
<article><h2>How the form reaches us</h2><p>When you submit the form, your details are sent to FormSubmit at formsubmit.co, which handles the spam check and emails the enquiry to CSC’s business inbox. FormSubmit says its submission archive is retained for 30 days. That is separate from any copy held in our email account.</p><p>Read <a href="https://formsubmit.co/privacy.pdf">FormSubmit’s privacy policy (PDF)</a> and <a href="https://formsubmit.co/documentation">submission documentation</a>. Its verification step may use Google reCAPTCHA, covered by <a href="https://policies.google.com/privacy">Google’s privacy policy</a>.</p></article>
<article><h2>Who else handles information</h2><p>Website hosting, form-delivery and email providers handle information needed to operate their services. The website hosting platform handles technical information needed to deliver and secure the pages. CSC’s enquiry form does not ask for account passwords.</p><p>Information relevant to a job may also need to be provided to professional advisers, insurers or authorities where needed to deal with an issue or meet a legal requirement. Service providers may operate internationally. Their privacy notices describe their processing; contact CSC if you need details about where your enquiry is handled and any applicable transfer safeguards.</p></article>
<article><h2>How long information is needed</h2><p>For enquiry correspondence, the relevant criteria are whether the enquiry is still active, whether a quotation or job needs follow-up, and whether a complaint or dispute remains unresolved. Job and financial records may need to be kept longer to meet legal obligations or deal with claims. A provider’s archive period does not automatically delete the email in CSC’s inbox. Contact us to ask about the retention of your particular enquiry.</p></article>
<article><h2>Cookies and website connections</h2><p>The website’s own code does not currently add advertising pixels, analytics tracking or visitor cookies. Hosting and sign-in services may use cookies and technical logs for access and security. FormSubmit and its spam-verification services have their own cookie practices when you submit an enquiry.</p><p>Fonts are loaded from Google Fonts, so your browser connects to Google when displaying the site. Those connections can disclose technical information such as your IP address and browser details. See <a href="https://policies.google.com/privacy">Google’s privacy policy</a> and <a href="https://vercel.com/legal/privacy-policy">Vercel’s privacy policy</a> for their services.</p></article>
<article><h2>Your privacy rights</h2><p>Depending on the circumstances and lawful basis, you can request access to your personal information, correction, deletion, restriction or a portable copy. If processing relies on consent, you may withdraw that consent without affecting processing already carried out lawfully.</p><p><strong>Your right to object:</strong> you can object to processing based on legitimate interests because of your particular situation, and you can object to direct marketing at any time. Contact CSC using the email or phone number above. We may need information to verify your identity before dealing with a request.</p><p>You can also complain to the UK Information Commissioner’s Office at <a href="https://ico.org.uk/make-a-complaint/">ico.org.uk/make-a-complaint</a>. You do not need to contact CSC first to exercise that right.</p></article>
<article><h2>Changes to this notice</h2><p>This notice should be read alongside any information supplied when arranging your job. We will update this page if the website or the way enquiries are handled changes.</p><Link className="button" to="/contact">Contact CSC</Link></article>
</section></>}
